Fix failing harvester test
This fixes the failing Harvester test:

```
  1) Harvester
       missing repo message should display when repo does NOT exist:
     CypressError: Timed out retrying after 10050ms: `cy.click()` failed because the center of this element is hidden from view:

`<li id="vsls-uid-oxhpdmahnqtk__option-0" role="option" class="vs__dropdown-option vs__dropdown-option--selected">...</li>`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at $Cy.ensureDescendents (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:147984:76)
      at ensureDescendents (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:133233:8)
      at ensureDescendentsAndScroll (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:133240:14)
      at ensureElIsNotCovered (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:133372:5)
      at runAllChecks (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:133562:52)
      at retryActionability (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:133586:16)
      at tryCatcher (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:11327:23)
      at Promise.attempt.Promise.try (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:8601:29)
      at whenStable (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:153059:65)
      at <unknown> (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:152468:14)
      at tryCatcher (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:11327:23)
      at Promise._settlePromiseFromHandler (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:9262:31)
      at Promise._settlePromise (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:9319:18)
      at Promise._settlePromise0 (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:9364:10)
      at Promise._settlePromises (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:9444:18)
      at Promise._fulfill (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:9388:18)
      at <unknown> (https://127.0.0.1.sslip.io/__cypress/runner/cypress_runner.js:11002:46)
  From Your Spec Code:
      at ./cypress/e2e/po/components/labeled-select.po.ts.LabeledSelectPo.clickOption (webpack:///./cypress/e2e/po/components/labeled-select.po.ts:35:0)
      at ./cypress/e2e/po/prompts/installExtensionDialog.po.ts.InstallExtensionDialog.selectVersionClick (webpack:///./cypress/e2e/po/prompts/installExtensionDialog.po.ts:43:0)
      at Context.eval (webpack:///./cypress/e2e/tests/pages/virtualization-mgmt/harvester.spec.ts:150:0)
```

This test passes when running the test locally in my environment. Not sure why it fails in CI at the moment.

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>